# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c4998c1a2992d3f5be006ee6b9a84425d5a4d15491d733885465b18a7199c146aeddbc5dbc60ee92946a068b6615d0385dfb20f0bd115f5ac340e32353a2094

test:
  secret_key_base: bcfc133c75337544aa69a0ca973475e322229f1db327dd987ad8773e100ecc621646ab0fe3b82c403f7b435c42b45f0daa99fbf0f5585ac771b8384c1432c904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
